name: Build and Upload WAR to Nexus Snapshot

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build WAR File
        run: mvn clean package -DskipTests

      - name: Configure Maven settings.xml for Nexus
        run: |
          mkdir -p ~/.m2
          cat <<EOF > ~/.m2/settings.xml
          <settings>
            <servers>
              <server>
                <id>nexus</id>
                <username>${{ secrets.NEXUS_USERNAME }}</username>
                <password>${{ secrets.NEXUS_PASSWORD }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Deploy Artifact to Nexus Snapshot Repository
        run: mvn deploy -DskipTests -DaltDeploymentRepository=nexus::default::${{ secrets.NEXUS_REPO_URL }}

      - name: Upload WAR Artifact to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: train-ticket-reservation-war
          path: target/*.war
